// network requests
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const RECEIVE_SELLERS = "RECEIVE_SELLERS";

export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const SHOW_CART_ITEMS = "SHOW_CART_ITEMS";

// application interactions
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SUBTRACT_CART_ITEM = "SUBTRACT_CART_ITEM";

export const LOAD_CATEGORY_ITEMS = "LOAD_CATEGORY_ITEMS";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const RECEIVE_SALES_DATA = "RECEIVE_SALES_DATA";

// place order
export const PLACE_ORDER = "PLACE_ORDER";

// checkout
export const REQUEST_CHECKOUT = "REQUEST_CHECKOUT";

// shop actions
export const RETRIEVE_SHOP = "RETRIEVE_SHOP";
export const RECIEVE_SHOP = "RECIEVE_SHOP";
export const ADD_SHOP = "ADD_SHOP";

// auth
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
